### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by gatesyp**
Signed-off-by: Steven Gates <steven@multisiglabs.org>

### CODE REVIEW

**Comment by gatesyp** [comment]
@agates4 plz. tests have passed. merge requested.

**Review by agates4 — APPROVED** [review]

**Comment by agates4** [comment]
thanks for valuable contribution.

**Comment by gatesyp** [comment]
thanks for yours too.

**Comment by gatesyp** [comment]
any chance of reward?

**Pull request merged**
